baseURL = "/"
languageCode = "en-us"
title = "AaronNBrock"
theme = "kube"
description = "But why?"
Paginate = 4

# pygmentsOptions="linenos=table"
pygmentsCodeFences=true
pygmentsStyle="tango"


[Params]
  RSSLink = "/index.xml"
  author = "AaronNBrock" # add your company name
  github = "AaronNBrock" # add your github profile name
  twitter = "AaronNBrock" # add your twitter profile
  email = "AaronNBrock@gmail.com"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
